/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/applications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Provides CRUD and state transition endpoints for Applications.
         *
         *     - Applicants can create, view, edit (in draft), and submit their own applications.
         *     - Reviewers can view all applications and perform state transitions.
         */
        get: operations["applications_list"];
        put?: never;
        /**
         * @description Creates a new application for the authenticated user.
         *
         *     The application is created with the requesting user as the owner.
         *
         *     Args:
         *         request: The request instance.
         *         *args: Variable length argument list.
         *         **kwargs: Arbitrary keyword arguments.
         *
         *     Returns:
         *         A Response object with the created application data.
         */
        post: operations["applications_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Retrieves a single application instance after checking permissions.
         *
         *     Args:
         *         request: The request instance.
         *         *args: Variable length argument list.
         *         **kwargs: Arbitrary keyword arguments.
         *
         *     Returns:
         *         A Response object with the application data.
         */
        get: operations["applications_retrieve"];
        /**
         * @description Provides CRUD and state transition endpoints for Applications.
         *
         *     - Applicants can create, view, edit (in draft), and submit their own applications.
         *     - Reviewers can view all applications and perform state transitions.
         */
        put: operations["applications_update"];
        post?: never;
        /**
         * @description Provides CRUD and state transition endpoints for Applications.
         *
         *     - Applicants can create, view, edit (in draft), and submit their own applications.
         *     - Reviewers can view all applications and perform state transitions.
         */
        delete: operations["applications_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Provides CRUD and state transition endpoints for Applications.
         *
         *     - Applicants can create, view, edit (in draft), and submit their own applications.
         *     - Reviewers can view all applications and perform state transitions.
         */
        patch: operations["applications_partial_update"];
        trace?: never;
    };
    "/api/applications/{id}/approve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Endpoint to transition an application from 'under_review' to 'approved'.
         *
         *     Args:
         *         request: The request instance.
         *         pk: The primary key of the application.
         *
         *     Returns:
         *         A Response object with the updated application data.
         */
        post: operations["applications_approve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{id}/audit-log/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Endpoint to retrieve the audit log for a specific application.
         *
         *     Args:
         *         request: The request instance.
         *         pk: The primary key of the application.
         *
         *     Returns:
         *         A Response object containing a list of audit log entries.
         */
        get: operations["applications_audit_log_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{id}/reject/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Endpoint to transition an application from 'under_review' to 'rejected'.
         *
         *     This action requires a comment.
         *
         *     Args:
         *         request: The request instance, containing a 'comment' in its body.
         *         pk: The primary key of the application.
         *
         *     Returns:
         *         A Response object with the updated application data or a validation error.
         */
        post: operations["applications_reject_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{id}/return-for-changes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Endpoint to transition an application from 'under_review' back to 'draft'.
         *
         *     This action requires a comment explaining why it's being returned.
         *
         *     Args:
         *         request: The request instance, containing a 'comment' in its body.
         *         pk: The primary key of the application.
         *
         *     Returns:
         *         A Response object with the updated application data or a validation error.
         */
        post: operations["applications_return_for_changes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{id}/start-review/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Endpoint to transition an application from 'submitted' to 'under_review'.
         *
         *     Args:
         *         request: The request instance.
         *         pk: The primary key of the application.
         *
         *     Returns:
         *         A Response object with the updated application data.
         */
        post: operations["applications_start_review_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{id}/submit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Endpoint to transition an application from 'draft' to 'submitted'.
         *
         *     Args:
         *         request: The request instance.
         *         pk: The primary key of the application.
         *
         *     Returns:
         *         A Response object with the updated application data.
         */
        post: operations["applications_submit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return the currently authenticated user and their role. */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Read-only serializer for the Application model, including nested data. */
        Application: {
            readonly id: number;
            readonly owner: components["schemas"]["User"];
            title: string;
            category: components["schemas"]["CategoryEnum"];
            description?: string;
            /** Format: decimal */
            amount?: string | null;
            readonly status: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly audit_logs: components["schemas"]["AuditLog"][];
        };
        /** @description Write serializer for creating and updating Application instances. */
        ApplicationWrite: {
            readonly id: number;
            readonly owner: number;
            title: string;
            category: components["schemas"]["CategoryEnum"];
            description?: string;
            /** Format: decimal */
            amount?: string | null;
            readonly status: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly audit_logs: components["schemas"]["AuditLog"][];
        };
        /** @description Serializer for the AuditLog model. */
        AuditLog: {
            readonly id: number;
            readonly actor: components["schemas"]["User"];
            from_status: string;
            to_status: string;
            comment?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `general` - General Request
         *     * `budget` - Budget Approval
         *     * `leave` - Leave Request
         *     * `procurement` - Procurement
         *     * `other` - Other
         * @enum {string}
         */
        CategoryEnum: "general" | "budget" | "leave" | "procurement" | "other";
        /** @description Write serializer for creating and updating Application instances. */
        PatchedApplicationWrite: {
            readonly id?: number;
            readonly owner?: number;
            title?: string;
            category?: components["schemas"]["CategoryEnum"];
            description?: string;
            /** Format: decimal */
            amount?: string | null;
            readonly status?: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            readonly audit_logs?: components["schemas"]["AuditLog"][];
        };
        /**
         * @description * `applicant` - Applicant
         *     * `reviewer` - Reviewer
         * @enum {string}
         */
        RoleEnum: "applicant" | "reviewer";
        /**
         * @description * `draft` - Draft
         *     * `submitted` - Submitted
         *     * `under_review` - Under Review
         *     * `approved` - Approved
         *     * `rejected` - Rejected
         * @enum {string}
         */
        StatusEnum: "draft" | "submitted" | "under_review" | "approved" | "rejected";
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        User: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /**
             * Email address
             * Format: email
             */
            email?: string;
            readonly role: components["schemas"]["RoleEnum"];
            first_name?: string;
            last_name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    applications_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"][];
                };
            };
        };
    };
    applications_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["ApplicationWrite"];
                "multipart/form-data": components["schemas"]["ApplicationWrite"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationWrite"];
                };
            };
        };
    };
    applications_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    applications_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["ApplicationWrite"];
                "multipart/form-data": components["schemas"]["ApplicationWrite"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationWrite"];
                };
            };
        };
    };
    applications_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedApplicationWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedApplicationWrite"];
                "multipart/form-data": components["schemas"]["PatchedApplicationWrite"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationWrite"];
                };
            };
        };
    };
    applications_approve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Application"];
                "application/x-www-form-urlencoded": components["schemas"]["Application"];
                "multipart/form-data": components["schemas"]["Application"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    applications_audit_log_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    applications_reject_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Application"];
                "application/x-www-form-urlencoded": components["schemas"]["Application"];
                "multipart/form-data": components["schemas"]["Application"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    applications_return_for_changes_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Application"];
                "application/x-www-form-urlencoded": components["schemas"]["Application"];
                "multipart/form-data": components["schemas"]["Application"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    applications_start_review_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Application"];
                "application/x-www-form-urlencoded": components["schemas"]["Application"];
                "multipart/form-data": components["schemas"]["Application"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    applications_submit_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Application"];
                "application/x-www-form-urlencoded": components["schemas"]["Application"];
                "multipart/form-data": components["schemas"]["Application"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "ht" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
